# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4bb3902e7048c8775a8db193ff3a00dc4fb265061de03b92f754f17bbdff0504aff69c65a7b2c993a5e67038dc3470b93f4117ebab5b1ba4576122b36a2df8

test:
  secret_key_base: 5aa906c92668755e20a21974988c2efbf42ca40a9437f47e309773a0354a4f42262d066b84708abae4ee2773ec56dbfb027ac3c45cff1e02e1e2069604d9a9ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
